poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('register', views.register_request, name='register'),
    path('login', views.login_request, name='login'),
    path("logout", views.logout_request, name="logout"),
    #path("password_reset", views.password_reset_request, name="password_reset"),
    #path("password_confirm/<uidb64>/<token>/", views.password_confirm_request, name="password_confirm"),

    path("editor", views.editor, name="editor"),
    path("create", views.create, name='create')
]

polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField("date published")

    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, PasswordChangeForm
from django.contrib.auth.models import User

from polls.models import Question


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
class UserPasswordResetForm(PasswordResetForm):
	email = forms.EmailInput
	
class UserPasswordConfirmForm(PasswordChangeForm):
	password1 = forms.PasswordInput
	password2 = forms.PasswordInput

polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import datetime

from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from .models import Question, Choice
from .forms import NewUserForm, UserPasswordResetForm, UserPasswordConfirmForm

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:20]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def editor(request):
    return render(request=request, template_name="polls/editor.html")

def create(request):
    if request.method == "POST":
        question = Question.objects.create(
            question_text = request.POST["question_text"],
            pub_date = datetime.datetime.now(tz=timezone.utc)
        )
        for x in range(2, len(request.POST)):
            choice = Choice.objects.create(
                question = question,
                choice_text = list(request.POST.values())[x],
                votes = 0
            )
        return redirect ("polls:editor" )
    return redirect ("polls:editor")

def register_request(request):
    registerError = False
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("polls:index")
        registerError = True
    form = NewUserForm()
    return render (request=request, template_name="polls/register.html", context={"register_form":form, "registerError": registerError})

def login_request(request):
    loginError = False
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("polls:index")
            else:
                loginError = True
        else:
                loginError = True
    form = AuthenticationForm()
    return render (request=request, template_name="polls/login.html", context={"login_form":form, "loginError": loginError})

def logout_request(request):
    logout(request)
    return redirect ("polls:index")

'''
def password_reset_request(request):
    processError = False
    if request.method == "POST":
        form = UserPasswordResetForm(request)                                                       
        if form.is_valid():
            email = form.cleaned_data["email"]
            associatedUsers = User.objects.filter(Q(email=email))
            if associatedUsers.exists():
                for user in associatedUsers:
                    subject = "Password Reset Requested"
                    email_template_name = "polls/password_reset_email.html"
                    c = {
                        "email":user.email,
                        'domain':'127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, "jann.totterman@gmail.com" , [user.email], fail_silently=False, auth_password="kek")
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return render (request=request, template_name="polls/password_reset.html", context={"reset_form":form, "error": processError, "success": True})
            else:
                processError=True
        else:
            processError=True

    form = UserPasswordResetForm(request)
    return render (request=request, template_name="polls/password_reset.html", context={"reset_form":form, "error": processError, "success": False})


def password_confirm_request(request):
    processError = False
    form = UserPasswordConfirmForm(request)
    return render (request=request, template_name="polls/password_confirm.html", context={"confirm_form":form, "error": processError, "success": False})
    
'''

polls/templates/base.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <title>{% block title %}Polls{% endblock %}</title>
</head>

<body>
    <header>
        <h1><a href="{% url 'polls:index' %}">Polls</a></h1>
        <div>
            {% if user.is_authenticated %}
                Hello, {{user.username}} |  
                <a href="{% url 'polls:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'polls:login' %}">Login</a>
            {% endif %}
        </div>
    </header>
    {% block content %}
    {% endblock content %}
</body>

polls/templates/polls/detail.html

{% extends "base.html" %}

{% block content %}
<a href="{% url 'polls:index' %}">Back</a>

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
    <a href="{% url 'polls:results' question.id %}">See results</a>
    {% endblock content %}

polls/templates/polls/editor.html

{% extends "base.html" %}

{% block content %}
<a href="{% url 'polls:index' %}">Back</a>

<form action="{% url 'polls:create' %}" method="post">
    {% csrf_token %}
    <legend><h1><input type="text" name="question_text" placeholder="Question"></h1></legend>
    <div id="choices">
        <input type="text" name="choice_text0" placeholder="Choice"><br>
    </div>
    <button type="button" onclick="addField()">+</button>
    <input type="submit" value="Create">
</form>


<script>
    let i = 0
    function addField () {
        i++
        const fieldset = document.getElementById("choices")
        let field = document.createElement("input")
        field.type = "text"
        field.name = "choice_text" + i
        field.placeholder = "Choice"
        fieldset.append(field)
        fieldset.append(document.createElement("br"))
    }

</script>
{% endblock content %}

polls/templates/polls/index.html

{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
<h2>
    <a href="{% url 'polls:editor' %}">New poll</a>
</h2>
{% endif %}


<h3>
    Latest Polls
</h3>

{% if latest_question_list %}
    {% for question in latest_question_list %}
    <div class="pollItem">
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </div>
    {% endfor %}
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock content %}

polls/templates/polls/login.html

{% extends "base.html" %}

{% block content %}
    <a href="{% url 'polls:index' %}">Back</a>
    
    <h2>Login</h2>
    
    {% if loginError == True %}
    <p><b>Username or password is invalid</b></p>
    {% endif %}
    
    <form method="POST">
      {% csrf_token %}
      {{ login_form }}
      <button type="submit">Login</button>
    </form>
    <!--<p><a href="{% url 'polls:index' %}">Forgot your password?</a></p> change index to password_reset-->
    <p>Don't have an account? <a href="{% url 'polls:register' %}">Create an account</a>.</p>
{% endblock content %}

polls/templates/polls/password_confirm.html

{% extends "base.html" %}

{% block content %}
    <a href="{% url 'polls:index' %}">Back</a>
    
    <h2>Password Confirm</h2>

    {% if success == True %}
    <p><b>Successfully reset password</b></p>
    {% else %}

    {% if error == True %}
    <p><b>ERROR</b></p>
    {% endif %}
    
    <form method="POST">
      {% csrf_token %}
      {{ confirm_form }}
      <button type="submit">Reset password</button>
    </form>
    {% endif %}
{% endblock content %}

polls/templates/polls/password_reset.html

{% extends "base.html" %}

{% block content %}
    <a href="{% url 'polls:index' %}">Back</a>
    
    <h2>Password Reset</h2>

    {% if success == True %}
    <p><b>Successfully sent email</b></p>
    {% else %}
      
    {% if error == True %}
    <p><b>ERROR</b></p>
    {% endif %}
    
    <form method="POST">
      {% csrf_token %}
      {{ reset_form }}
      <button type="submit">Send reset link</button>
    </form>
    {% endif %}
{% endblock content %}

polls/templates/polls/password_reset_email.html
{% autoescape off %}
Hello,

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'polls:password_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
The Website Team

{% endautoescape %}

polls/templates/polls/register.html

{% extends "base.html" %}

{% block content %}
<a href="{% url 'polls:index' %}">Back</a>
	<h1>Register</h1>
	{% if registerError == True %}
	<b>Unsuccessful registration. Invalid information.</b>
	{% endif %}
	<form method="POST">
		{% csrf_token %}
		{{ register_form }}                    
		<button type="submit">Register</button>
	</form>
	<p>If you already have an account, <a href="{% url 'polls:login' %}">login</a> instead.</p>
	{% endblock content %}

polls/templates/polls/results.html

{% extends "base.html" %}

{% block content %}
<a href="{% url 'polls:index' %}">Back to polls</a>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}